---
kind: pipeline
type: docker
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: acim/go-reflex
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
    - GO_VERSION=1.13.3-buster
    tags:
    - 1.13.3-buster
    - latest
    - stable