---
kind: pipeline
type: docker
name: default

steps:
- name: build  
  image: ablab/drone-kaniko
  settings:
    repo: acim/go-reflex
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
    - 1.13.5-0
    - latest
    - stable